import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
const mocks = vi.hoisted(() => ({ auth: vi.fn(), snapshot: vi.fn(), persist: vi.fn(), claim: vi.fn(), release: vi.fn(), abandon: vi.fn(), finalize: vi.fn(), cancel: vi.fn(), failure: vi.fn(), record: vi.fn() }))
vi.mock("@daytonaio/sdk", () => ({ Daytona: class { async get() { return { process: { executeCommand: async () => ({ result: "no" }) } } } } }))
vi.mock("@/lib/db/api-helpers", () => ({ requireChatStreamAccess: mocks.auth, isAuthError: (value: unknown) => value instanceof Response }))
vi.mock("@/lib/db/prisma", () => ({ prisma: { chat: { findUnique: vi.fn(async () => null) } } }))
vi.mock("@/lib/agent-session", () => ({ snapshotBackgroundAgent: mocks.snapshot, finalizeTurn: mocks.finalize, cancelBackgroundAgent: mocks.cancel, formatAgentError: (error: Error) => error.message }))
vi.mock("@/lib/server/turn-ownership", () => ({ claimTurnFinalization: mocks.claim, releaseTurn: mocks.release, abandonFinalization: mocks.abandon }))
vi.mock("@/lib/server/turn-failure", () => ({ readTurnFailure: mocks.failure, recordTurnFailure: mocks.record }))
vi.mock("./_lib/persist-snapshot", () => ({ persistAgentSnapshot: mocks.persist }))
vi.mock("@/lib/db/activity-log", () => ({ logLlmProviderError: vi.fn() }))
vi.mock("@/lib/server/token-metering", () => ({ meterAssistantTurn: vi.fn() }))
vi.mock("@/lib/git/auto-push", () => ({ autoPushChat: vi.fn() }))
vi.mock("@/lib/server/uncommitted-files-warning", () => ({ refreshUncommittedFilesWarning: vi.fn() }))
import { GET } from "./route"

const turn = { chatId: "chat", backgroundSessionId: "session", assistantMessageId: "assistant" }
beforeEach(() => {
  vi.resetAllMocks()
  vi.stubEnv("DAYTONA_API_KEY", "test-only")
  vi.spyOn(console, "error").mockImplementation(() => {})
  mocks.auth.mockResolvedValue({ userId: "user", chat: { id: "chat", sandboxId: "sandbox", backgroundSessionId: "session", repo: "__new__", branch: null } })
  mocks.snapshot.mockResolvedValue({ status: "completed", content: "complete answer", toolCalls: [], contentBlocks: [] })
  mocks.persist.mockResolvedValue({ persisted: true })
  mocks.claim.mockResolvedValue("claim")
  mocks.release.mockResolvedValue(true)
  mocks.failure.mockResolvedValue(null)
  mocks.record.mockResolvedValue(true)
})
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllEnvs(); vi.useRealTimers() })
const stream = async () => (await GET(new Request("http://localhost/api/agent/stream?chatId=chat&assistantMessageId=assistant"))).text()

describe("stream finalization durability", () => {
  it("retains the recoverable turn when its final snapshot cannot be saved", async () => {
    mocks.persist.mockResolvedValue({ persisted: false })
    const frames = await stream()
    expect(mocks.release).not.toHaveBeenCalled()
    expect(mocks.abandon).toHaveBeenCalledWith(turn, "claim")
    expect(frames).not.toContain("event: complete")
    expect(frames).toContain("event: error")
  })
  it("saves and releases on a successful finalization", async () => {
    const frames = await stream()
    expect(mocks.persist).toHaveBeenCalledWith(expect.objectContaining({ turn, finalizationClaimId: "claim" }))
    expect(mocks.release).toHaveBeenCalledWith(turn, "claim", "ready", undefined)
    expect(frames).toContain("event: complete")
    expect(mocks.persist.mock.invocationCallOrder[0]).toBeLessThan(mocks.finalize.mock.invocationCallOrder[0])
  })
  it("recovers a cancelled timeout as an error even when the SDK reports completed", async () => {
    mocks.failure.mockResolvedValue({ reason: "Run exceeded its limit", executionStopped: false })
    const frames = await stream()
    expect(mocks.cancel).toHaveBeenCalledWith(expect.anything(), "session", expect.anything(), true)
    expect(mocks.record).toHaveBeenCalledWith(turn, "claim", "Run exceeded its limit", true)
    expect(mocks.release).toHaveBeenCalledWith(turn, "claim", "error", undefined)
    expect(frames).toContain("Run exceeded its limit")
  })
  it("does not release after a failed confirmed-terminal marker write", async () => {
    mocks.failure.mockResolvedValue({ reason: "timeout" })
    mocks.record.mockResolvedValueOnce(true).mockRejectedValueOnce(new Error("Database failed"))
    const frames = await stream()
    expect(mocks.release).not.toHaveBeenCalled()
    expect(frames).toContain("event: error")
  })
  it("does not release or label the agent failed when only the stream transport fails", async () => {
    mocks.snapshot.mockRejectedValue(new Error("transport unavailable"))
    const frames = await stream()
    expect(mocks.claim).not.toHaveBeenCalled()
    expect(mocks.release).not.toHaveBeenCalled()
    expect(frames).toContain("event: error")
  })
  it("keeps the real execution alive after repeated unavailable snapshot reads", async () => {
    vi.useFakeTimers()
    mocks.snapshot.mockResolvedValue({ status: "error", content: "partial", toolCalls: [], contentBlocks: [], transientReadFailure: true })
    const reading = stream()
    await vi.advanceTimersByTimeAsync(6000)
    const frames = await reading
    expect(mocks.snapshot).toHaveBeenCalledTimes(10)
    expect(mocks.cancel).not.toHaveBeenCalled()
    expect(mocks.claim).not.toHaveBeenCalled()
    expect(mocks.release).not.toHaveBeenCalled()
    expect(frames).toContain("event: error")
    expect(frames).not.toContain("event: complete")
  })
})
